### ISSUE TITLE
Task in ECS warning, cannot find the runner in Gitlab

### ISSUE THREAD

**Issue by alesiobitaGit** [GovTechSG/fargate-gitlab-runner-terraform#4]
Hi, 
I install the Gitlab Runner in ECS Fargate and didn't receive any error in Infrastructure side. Even the Task in ECS Fargate is in RUN Status but it has an error like below:
<img width="1712" alt="Screenshot 2023-01-26 at 10 54 53" src="https://user-images.githubusercontent.com/69250887/214807182-85233e1c-00aa-4730-b676-b59c54c567d5.png">

     gitlab_url                              = "https://gitlab.com/"
    gitlab_runner_concurrency = 10
    gitlab_runner_name_prefix = "ecs-fargate"

Thanks for your support and for every advice I would be happy : )

**Comment by mateusmcordeiro** [comment]
same here, how did you fix it?
